### ISSUE TITLE
Missing URL to docs website from GitHub repository or README

### ISSUE THREAD

**Issue by justwheel** [tillioss/tilli-docs#10]
There is not a link to the [hosted documentation site](https://tillioss.github.io/tilli-docs/) built from this repository. The URL should be added in two places:

1. GitHub repository infobox (found in upper-right on the _Code_ tab of repository)
2. Linked from repo README.md file

**Example 1**:

![Screenshot of repository infobox. This is the Tilli-docs repository. Someone with access will have a gear-shaped icon they can click and edit information about the repository. One option is a URL field, which will show up in the repository and in GitHub search.](https://user-images.githubusercontent.com/4721034/205385489-4a226d0d-f536-4c12-806c-b07adc2a5c91.png "Screenshot of repository infobox. This is the Tilli-docs repository. Someone with access will have a gear-shaped icon they can click and edit information about the repository. One option is a URL field, which will show up in the repository and in GitHub search.")

Reference: https://tillioss.github.io/tilli-docs/

**Comment by Hannah31George** [comment]
Instead of the above [landing page](https://tillioss.github.io/tilli-docs/), we have linked a new landing page that is on our website. Kindly visit: https://www.tillikids.com/opensource

**Comment by Hannah31George** [comment]
We have sent the list of descriptions that needs to be updated (About Section) of each repo to Ravi's team. They are currently updating the same.

**Comment by justwheel** [comment]
> Instead of the above [landing page](https://tillioss.github.io/tilli-docs/), we have linked a new landing page that is on our website. Kindly visit: https://www.tillikids.com/opensource

Could you clarify the purpose of this existing site?

> We have sent the list of descriptions that needs to be updated (About Section) of each repo to Ravi's team. They are currently updating the same.

Could you also clarify which page or section is being updated?

**Comment by Hannah31George** [comment]
Hello Justin,

1. Instead of the above [landing page](https://tillioss.github.io/tilli-docs/), we have linked a new landing page that is on our website. Kindly visit: https://www.tillikids.com/opensourceCould you clarify the purpose of this existing site?

-  Our main website is [www.tillikids.com](http://www.tillikids.com/), and we would have more traction of users coming into our website and wanted to add a page that took users to the open-source documentation.

- We were also facing issues in updating only the [landing page section](https://tillioss.github.io/) and wanted a more user-friendly landing page that opened the Project Charter (https://tillioss.github.io/docs/project-charter/)


2. We have sent the list of descriptions that needs to be updated (About Section) of each repo to Ravi's team. They are currently updating the same.

Could you also clarify which page or section is being updated?

- Kindly find the screenshots attached below for the respective pages:

![image](https://user-images.githubusercontent.com/108776565/205654596-d2e7f20d-987f-46b2-a8c1-411bcacac0ba.png)

![image (1)](https://user-images.githubusercontent.com/108776565/205654659-dd5fdd57-3ec0-49de-af12-dcd53ece8575.png)

![image (2)](https://user-images.githubusercontent.com/108776565/205654683-7e3ee86d-5278-4f5e-9857-8a15d25509af.png)

![image (3)](https://user-images.githubusercontent.com/108776565/205654697-28b64113-84f6-4404-a6f6-fb4b85cd1601.png)

**Comment by justwheel** [comment]
Thanks for this @Hannah31George 👍🏻 Now I understand what you mean about updating the _About_ section. Makes sense!

In our call today, I am thinking we can discuss these options in more detail and figure out an approach that works best for the Tilli team:

1. **Unifying to one documentation site**
    * **Strength**: One universal place to find information and make changes.
    * **Weakness**: Not possible for external contributors to contribute or make changes.
    * **Opportunity**: A smoother onboarding experience for an external contributor or newcomer to the project.
    * **Threat**: Requires revisions to UNICEF Venture Fund workplan.
2. **Using a developer/contributor portal on main site, and open docs for project/developer information**
    * **Strength**: Two different sites for different audiences. Each audience is better able to find the specific details they are looking for.
    * **Weakness**: Requires organization to ensure the two sites are aligned and do not contradict each other.
    * **Opportunity**: Better messaging on the Open Source approach, where the main website is for partners, investors, and media, while the developer docs are for contributors, involved stakeholders, and day-to-day participants in the project.
    * **Threat**: Unclear policy for what content goes on which site and how information is updated on one site or the other.
